export const movie_list = [
  {
    id: 1,
    image: '1.jpg',
    title: 'İkinci Bahar',
    description: 'Tv Series',
    is_active: true,
    is_new: true,
    imd: 8.7,
    href: 'https://www.youtube.com/playlist?list=PLBe40ko4AI0XHc321cxXFzjj9BuqKsREj',
  },
  {
    id: 2,
    image: '2.jpg',
    title: 'Çemberimde Gül Oya',
    description: 'Tv Series',
    is_active: true,
    is_new: true,
    imd: 8.8,
    href: 'https://www.youtube.com/playlist?list=PL6nM1RK5nFKcypLVXRvmFBxMUBhVkQsIn',
  },
  {
    id: 3,
    image: '3.jpg',
    title: 'Canım Ailem',
    description: 'Tv Series',
    is_active: true,
    is_new: true,
    imd: 7.4,
    href: 'https://www.youtube.com/playlist?list=PLRY6z6O2ULCL9sqe2zwDkgcBjhtJ4HCnt',
  },
  {
    id: 4,
    image: '4.webp',
    title: 'Yaprak Dökümü',
    description: 'Tv Series',
    is_active: true,
    is_new: true,
    imd: 5.9,
    href: 'https://www.youtube.com/playlist?list=PLVxfBEU9q9SI4WMoxAcGwCeH5tZ58IZMY',
  },
  {
    id: 5,
    image: '5.jpg',
    title: 'Aşk-ı Memnu',
    description: 'Tv Series',
    is_active: true,
    is_new: true,
    imd: 7.6,
    href: 'https://www.youtube.com/playlist?list=PLcrYdKVzfF1SW5S9na2xGv5BPatFQWgxy',
  },
  {
    id: 6,
    image: '11.jpg',
    title: 'Avrupa Yakası',
    description: 'Tv Series',
    is_active: true,
    is_new: true,
    imd: 8.6,
    href: 'https://www.youtube.com/playlist?list=PLDBem4OrlfANat0Ah-npw8EcuaX50Ls-q',
  },
  {
    id: 7,
    image: '12.jpeg',
    title: 'Yalan Dünya',
    description: 'Tv Series',
    is_active: true,
    is_new: true,
    imd: 7.2,
    href: 'https://www.youtube.com/playlist?list=PLkqqLwNlIfFKqbFmpXvIC4uO9-BZpWzPh',
  },
  {
    id: 8,
    image: '8.jpg',
    title: 'Merhamet',
    description: 'Tv Series',
    is_active: true,
    is_new: true,
    imd: 7.5,
    href: 'https://www.youtube.com/playlist?list=PL9JGLb9aU05_dsdkOgQ4CWad5AiJNcUf4',
  },
  {
    id: 9,
    image: '9.jpg',
    title: 'Kadın İsterse',
    description: 'Tv Series',
    is_active: true,
    is_new: true,
    imd: 3.7,
    href: 'https://www.youtube.com/playlist?list=PLwXaaAWFNr9j5j5R4PdmLAhfaiqZ7Gtv2',
  },
  {
    id: 10,
    image: '10.jpg',
    title: 'Şaşıfelek Çıkmazı',
    description: 'Tv Series',
    is_active: true,
    is_new: true,
    imd: 8.7,
    href: 'https://www.youtube.com/playlist?list=PLm3-FYEZRvRd6tL5e--NJzodp8gSvdrvg',
  },
  {
    id: 11,
    image: '6.jpg',
    title: 'Kızılcık Şerbeti',
    description: 'Tv Series',
    is_active: true,
    is_new: true,
    imd: 5.5,
    href: 'https://www.youtube.com/playlist?list=PLusr3qjmF4tA8NqLIba4SEhtyWkL9G6uz',
  },
  {
    id: 12,
    image: '7.png',
    title: 'Yeditepe İstanbul',
    description: 'Dram',
    is_active: true,
    is_new: true,
    imd: 8.6,
    href: 'https://www.youtube.com/playlist?list=PLm3-FYEZRvRdj8RZSJt-aVVZd1ksA2OVb',
  },
];
